import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import {  Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], weight:['400', '500', '700', '800'], display: 'swap' });

export const metadata = {
  title: "Writify",
  description: "Generated by create next app",
  icons:{
    icon: '/icons8-blog-50.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
